/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ClickCounter {}
  interface FizzBuzz {}
  interface ModalPopup {}
  interface ModalTrigger {}
  interface NameTag {
    'name': string;
  }
  interface TabPanel {}
}

declare global {


  interface HTMLClickCounterElement extends Components.ClickCounter, HTMLStencilElement {}
  var HTMLClickCounterElement: {
    prototype: HTMLClickCounterElement;
    new (): HTMLClickCounterElement;
  };

  interface HTMLFizzBuzzElement extends Components.FizzBuzz, HTMLStencilElement {}
  var HTMLFizzBuzzElement: {
    prototype: HTMLFizzBuzzElement;
    new (): HTMLFizzBuzzElement;
  };

  interface HTMLModalPopupElement extends Components.ModalPopup, HTMLStencilElement {}
  var HTMLModalPopupElement: {
    prototype: HTMLModalPopupElement;
    new (): HTMLModalPopupElement;
  };

  interface HTMLModalTriggerElement extends Components.ModalTrigger, HTMLStencilElement {}
  var HTMLModalTriggerElement: {
    prototype: HTMLModalTriggerElement;
    new (): HTMLModalTriggerElement;
  };

  interface HTMLNameTagElement extends Components.NameTag, HTMLStencilElement {}
  var HTMLNameTagElement: {
    prototype: HTMLNameTagElement;
    new (): HTMLNameTagElement;
  };

  interface HTMLTabPanelElement extends Components.TabPanel, HTMLStencilElement {}
  var HTMLTabPanelElement: {
    prototype: HTMLTabPanelElement;
    new (): HTMLTabPanelElement;
  };
  interface HTMLElementTagNameMap {
    'click-counter': HTMLClickCounterElement;
    'fizz-buzz': HTMLFizzBuzzElement;
    'modal-popup': HTMLModalPopupElement;
    'modal-trigger': HTMLModalTriggerElement;
    'name-tag': HTMLNameTagElement;
    'tab-panel': HTMLTabPanelElement;
  }
}

declare namespace LocalJSX {
  interface ClickCounter {}
  interface FizzBuzz {}
  interface ModalPopup {}
  interface ModalTrigger {
    'onOpenModal'?: (event: CustomEvent<any>) => void;
  }
  interface NameTag {
    'name'?: string;
  }
  interface TabPanel {}

  interface IntrinsicElements {
    'click-counter': ClickCounter;
    'fizz-buzz': FizzBuzz;
    'modal-popup': ModalPopup;
    'modal-trigger': ModalTrigger;
    'name-tag': NameTag;
    'tab-panel': TabPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'click-counter': LocalJSX.ClickCounter & JSXBase.HTMLAttributes<HTMLClickCounterElement>;
      'fizz-buzz': LocalJSX.FizzBuzz & JSXBase.HTMLAttributes<HTMLFizzBuzzElement>;
      'modal-popup': LocalJSX.ModalPopup & JSXBase.HTMLAttributes<HTMLModalPopupElement>;
      'modal-trigger': LocalJSX.ModalTrigger & JSXBase.HTMLAttributes<HTMLModalTriggerElement>;
      'name-tag': LocalJSX.NameTag & JSXBase.HTMLAttributes<HTMLNameTagElement>;
      'tab-panel': LocalJSX.TabPanel & JSXBase.HTMLAttributes<HTMLTabPanelElement>;
    }
  }
}


